//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagerM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionStepResult
    {
        public int QuestionStepResultID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public int CreateUserRole { get; set; }
        public string Content { get; set; }
        public int ActionID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Question Question { get; set; }
    }
}
